### ISSUE TITLE
Can not connect to database

### ISSUE THREAD

**Issue by adiatma85** [victorsteven/Dockerized-Golang-Postgres-Mysql-API#3]
Hello @victorsteven , first, I like to say thank you about the tutorial that you write [here](https://levelup.gitconnected.com/dockerized-crud-restful-api-with-go-gorm-jwt-postgresql-mysql-and-testing-61d731430bd8)

I have some kind of problem when use this repository as reference, when I run ``docker-compose up``
the app can not run and have error messages like this
![image](https://user-images.githubusercontent.com/57523711/163703595-c5763cd3-4a34-4a84-857a-670376d2e1d1.png)

In docker-compose.yml, the configuration is like this
```yml
fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
```
(It's sync with .env file)
I can not figure out why I found error while running docker-compose, but I can assure that mysql container is running

Any one have a lead why this is happen?
Thanks in advance
